/**
 * storeProject.js — генератор полного React-проекта магазина для ZIP-экспорта
 * (спецификация §9). Возвращает плоское дерево { 'path': 'content' }.
 *
 * Безопасность: в проект НЕ попадают секреты (SERVICE_ROLE, PAYMENT_SECRET,
 * OPENROUTER, sb_secret_) — только publishable anon key (публичен по дизайну,
 * так же встраивается в widget.js) и ссылка на app origin.
 * Проверяется тестом storeProject.test.js.
 *
 * Данные проект читает сам через get_public_business, заказ валидируется
 * сервером через RPC create_store_order — frontend-цены не считаются авторитетными.
 */

const slugify = (s) => String(s || 'store')
  .toLowerCase()
  .replace(/[^a-z0-9]+/g, '-')
  .replace(/^-+|-+$/g, '')
  .slice(0, 40) || 'store';

/** Дерево файлов проекта. */
export function buildStoreProject({
  name = 'Магазин',
  description = '',
  businessId = '',
  supabaseUrl = '',
  anonKey = '',
  appOrigin = '',
} = {}) {
  const projectName = slugify(name);
  const title = String(name || 'Магазин').slice(0, 80);
  const files = {};

  files['package.json'] = JSON.stringify({
    name: projectName,
    private: true,
    version: '1.0.0',
    type: 'module',
    scripts: { dev: 'vite', build: 'vite build', preview: 'vite preview' },
    dependencies: { react: '^18.3.1', 'react-dom': '^18.3.1' },
    devDependencies: { '@vitejs/plugin-react': '^4.3.4', vite: '^6.0.0' },
  }, null, 2);

  files['index.html'] = [
    '<!doctype html>',
    '<html lang="ru">',
    '  <head>',
    '    <meta charset="UTF-8" />',
    '    <meta name="viewport" content="width=device-width, initial-scale=1.0" />',
    `    <title>${escapeHtml(title)}</title>`,
    '  </head>',
    '  <body>',
    '    <div id="root"></div>',
    '    <script type="module" src="/src/main.jsx"></script>',
    '  </body>',
    '</html>',
  ].join('\n');

  files['vite.config.js'] = [
    "import { defineConfig } from 'vite';",
    "import react from '@vitejs/plugin-react';",
    '',
    'export default defineConfig({',
    '  plugins: [react()],',
    '});',
  ].join('\n');

  files['.env.example'] = [
    '# Публичный адрес приложения Karta-AD (ссылки на трекинг и поддержку)',
    `VITE_KARTA_API_URL=${appOrigin || 'https://karta-ad.vercel.app'}`,
    '# ID вашего бизнеса в Karta-AD',
    `VITE_BUSINESS_ID=${businessId}`,
    '# Никаких серверных ключей сюда не кладите: publishable anon key',
    '# уже вшит в src/lib/kartaApi.js — он публичен по дизайну.',
  ].join('\n');

  files['README.md'] = [
    `# ${title}`,
    '',
    description ? `> ${description}` : '',
    '',
    'Магазин, экспортированный из Karta-AD. Каталог, корзина, доставка',
    'и оплата; заказы провалидируются на сервере Karta-AD (цены, остатки,',
    'минимальная сумма).',
    '',
    '## Запуск',
    '',
    '```bash',
    'cp .env.example .env.local   # заполните VITE_BUSINESS_ID',
    'npm install',
    'npm run dev',
    '```',
    '',
    '## Сборка',
    '',
    '```bash',
    'npm run build   # результат в dist/ — выкладывайте на любой хостинг',
    '```',
    '',
  ].filter((l) => l !== '').join('\n').replace(/\n{3,}/g, '\n\n');

  files['src/main.jsx'] = [
    "import React from 'react';",
    "import { createRoot } from 'react-dom/client';",
    "import App from './App.jsx';",
    "import './styles.css';",
    '',
    "createRoot(document.getElementById('root')).render(",
    '  <React.StrictMode>',
    '    <App />',
    '  </React.StrictMode>,',
    ');',
  ].join('\n');

  files['src/lib/kartaApi.js'] = buildKartaApi({ supabaseUrl, anonKey, businessId });

  files['src/App.jsx'] = buildApp();
  files['src/styles.css'] = STYLES_CSS;
  files['src/components/Header.jsx'] = COMPONENT_HEADER;
  files['src/components/Hero.jsx'] = COMPONENT_HERO;
  files['src/components/ProductGrid.jsx'] = COMPONENT_PRODUCT_GRID;
  files['src/components/Cart.jsx'] = COMPONENT_CART;
  files['src/components/Checkout.jsx'] = COMPONENT_CHECKOUT;
  files['src/components/Delivery.jsx'] = COMPONENT_DELIVERY;
  files['src/components/Payment.jsx'] = COMPONENT_PAYMENT;
  files['src/components/Footer.jsx'] = COMPONENT_FOOTER;

  return files;
}

function escapeHtml(s) {
  return String(s).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
}

/**
 * API-клиент проекта: publishable anon key вшит (не секрет),
 * заказ уходит только через RPC create_store_order — сервер
 * пересчитывает цены, доставку и лимиты сам.
 */
function buildKartaApi({ supabaseUrl, anonKey, businessId }) {
  return [
    '/**',
    ' * kartaApi.js — клиент API Karta-AD для этого магазина.',
    ' * Publishable anon key вшит намеренно: он публичен по дизайну',
    ' * (как в официальном виджете Karta-AD). Секретов в файле нет.',
    ' */',
    "const SUPABASE_URL = '" + String(supabaseUrl) + "';",
    "const ANON_KEY = '" + String(anonKey) + "';",
    'const DEFAULT_BUSINESS_ID =',
    "  (import.meta.env.VITE_BUSINESS_ID || '" + String(businessId) + "')",
    '    .trim();',
    '',
    'export function businessId() {',
    '  if (!DEFAULT_BUSINESS_ID) {',
    "    throw new Error('Задайте VITE_BUSINESS_ID в .env.local');",
    '  }',
    '  return DEFAULT_BUSINESS_ID;',
    '}',
    '',
    'const BIZ_ID_RE =',
    "  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;",
    '',
    'function headers() {',
    '  return {',
    '    apikey: ANON_KEY,',
    "    Authorization: 'Bearer ' + ANON_KEY,",
    "    'Content-Type': 'application/json',",
    '  };',
    '}',
    '',
    'async function rpc(name, body) {',
    '  const res = await fetch(SUPABASE_URL + "/rest/v1/rpc/" + name, {',
    "    method: 'POST',",
    '    headers: headers(),',
    '    body: JSON.stringify(body),',
    '  });',
    '  if (!res.ok) {',
    '    const text = await res.text().catch(() => "");',
    '    let message = text;',
    '    try { message = JSON.parse(text).message || text; } catch { /* оставляем текст */ }',
    "    throw new Error(name + ': HTTP ' + res.status + ' ' + message);",
    '  }',
    '  return res.json();',
    '}',
    '',
    '/** Публичный каталог + настройки сайта (без auth). */',
    'export async function fetchStore() {',
    '  const id = businessId();',
    '  if (!BIZ_ID_RE.test(id)) throw new Error("VITE_BUSINESS_ID: ожидается UUID");',
    "  const data = await rpc('get_public_business', { p_business_id: id });",
    '  if (!data) throw new Error("Магазин не найден или не активен");',
    '  return data;',
    '}',
    '',
    '/**',
    ' * Создать заказ. Цены НЕ передаются — сервер берёт их из каталога',
    ' * (create_store_order: пересчёт цен, остатки, доставка, rate-limit).',
    ' */',
    'export async function createStoreOrder({ items, customer, delivery, paymentMethod }) {',
    '  return rpc("create_store_order", {',
    '    p_business_id: businessId(),',
    '    p_items: items,',
    '    p_customer: customer,',
    '    p_delivery: delivery,',
    '    p_payment_method: paymentMethod,',
    '  });',
    '}',
    '',
  ].join('\n');
}

function buildApp() {
  return [
    "import { useEffect, useMemo, useState } from 'react';",
    "import { fetchStore } from './lib/kartaApi.js';",
    "import Header from './components/Header.jsx';",
    "import Hero from './components/Hero.jsx';",
    "import ProductGrid from './components/ProductGrid.jsx';",
    "import Cart from './components/Cart.jsx';",
    "import Checkout from './components/Checkout.jsx';",
    "import Delivery from './components/Delivery.jsx';",
    "import Payment from './components/Payment.jsx';",
    "import Footer from './components/Footer.jsx';",
    '',
    'export default function App() {',
    '  const [store, setStore] = useState(null);',
    '  const [error, setError] = useState("");',
    '  const [cart, setCart] = useState({});',
    '  const [cartOpen, setCartOpen] = useState(false);',
    '',
    '  useEffect(() => {',
    '    fetchStore().then(setStore).catch((e) => setError(e.message));',
    '  }, []);',
    '',
    '  const add = (id) => setCart((c) => ({ ...c, [id]: (c[id] || 0) + 1 }));',
    '  const setQty = (id, qty) => setCart((c) => {',
    '    const next = { ...c };',
    '    if (qty <= 0) delete next[id];',
    '    else next[id] = Math.min(99, qty);',
    '    return next;',
    '  });',
    '',
    '  const items = useMemo(() => {',
    '    const byId = new Map((store?.products || []).map((p) => [p.id, p]));',
    '    return Object.entries(cart)',
    '      .map(([id, quantity]) => {',
    '        const product = byId.get(id);',
    '        return product ? { product_id: id, quantity, product } : null;',
    '      })',
    '      .filter(Boolean);',
    '  }, [cart, store]);',
    '',
    '  const subtotal = items.reduce(',
    '    (sum, it) => sum + Number(it.product.price) * it.quantity, 0,',
    '  );',
    '',
    '  if (error) return <main className="page"><p className="error">{error}</p></main>;',
    '  if (!store) return <main className="page"><p className="muted">Загрузка…</p></main>;',
    '',
    '  const settings = store.website_settings || {};',
    '',
    '  return (',
    '    <div className="app">',
    '      <Header name={store.name} count={items.length} onCart={() => setCartOpen(true)} />',
    '      <main className="page">',
    '        <Hero store={store} settings={settings} />',
    '        <ProductGrid products={store.products || []} cart={cart} onAdd={add} onQty={setQty} />',
    '        {settings.show_delivery !== false && <Delivery settings={settings} subtotal={subtotal} />}',
    '        {settings.show_payment !== false && <Payment settings={settings} />}',
    '        <Footer store={store} />',
    '      </main>',
    '      {cartOpen && (',
    '        <div className="overlay" role="presentation" onClick={() => setCartOpen(false)}>',
    '          <div className="sheet" onClick={(e) => e.stopPropagation()}>',
    '            <Cart items={items} subtotal={subtotal} onQty={setQty} onClose={() => setCartOpen(false)} />',
    '            <Checkout',
    '              items={items}',
    '              settings={settings}',
    '              onDone={() => { setCart({}); setCartOpen(false); }}',
    '            />',
    '          </div>',
    '        </div>',
    '      )}',
    '    </div>',
    '  );',
    '}',
  ].join('\n');
}

const COMPONENT_HEADER = [
  'export default function Header({ name, count, onCart }) {',
  '  return (',
  '    <header className="header">',
  '      <span className="logo">{name}</span>',
  '      <button className="btn ghost" onClick={onCart} type="button">',
  '        Корзина{count ? ` (${count})` : ""}',
  '      </button>',
  '    </header>',
  '  );',
  '}',
].join('\n');

const COMPONENT_HERO = [
  'export default function Hero({ store, settings }) {',
  '  const title = settings.hero_title || store.name;',
  '  const text = settings.hero_description || store.description || "";',
  '  return (',
  '    <section className="hero">',
  '      <h1>{title}</h1>',
  '      {text && <p className="muted">{text}</p>}',
  '      <a className="btn" href="#catalog">К покупкам</a>',
  '    </section>',
  '  );',
  '}',
].join('\n');

const COMPONENT_PRODUCT_GRID = [
  'function money(v) {',
  '  return `${Number(v).toFixed(0)} TJS`;',
  '}',
  '',
  'export default function ProductGrid({ products, cart, onAdd, onQty }) {',
  '  return (',
  '    <section id="catalog" className="grid-wrap">',
  '      <h2>Каталог</h2>',
  '      {products.length === 0 && <p className="muted">Товары скоро появятся</p>}',
  '      <div className="grid">',
  '        {products.map((p) => {',
  '          const qty = cart[p.id] || 0;',
  '          return (',
  '            <article className="card" key={p.id}>',
  '              {p.image_url && <img src={p.image_url} alt="" loading="lazy" />}',
  '              <h3>{p.name}</h3>',
  '              {p.description && <p className="muted">{p.description}</p>}',
  '              <strong>{money(p.price)}</strong>',
  '              {qty === 0 ? (',
  '                <button className="btn" type="button" onClick={() => onAdd(p.id)}>В корзину</button>',
  '              ) : (',
  '                <div className="qty">',
  '                  <button type="button" onClick={() => onQty(p.id, qty - 1)}>−</button>',
  '                  <span>{qty}</span>',
  '                  <button type="button" onClick={() => onQty(p.id, qty + 1)}>+</button>',
  '                </div>',
  '              )}',
  '            </article>',
  '          );',
  '        })}',
  '      </div>',
  '    </section>',
  '  );',
  '}',
].join('\n');

const COMPONENT_CART = [
  'function money(v) {',
  '  return `${Number(v).toFixed(0)} TJS`;',
  '}',
  '',
  'export default function Cart({ items, subtotal, onQty, onClose }) {',
  '  return (',
  '    <div className="cart">',
  '      <div className="cart-head">',
  '        <h2>Корзина</h2>',
  '        <button className="btn ghost" type="button" onClick={onClose}>✕</button>',
  '      </div>',
  '      {items.length === 0 && <p className="muted">Корзина пуста</p>}',
  '      <ul className="cart-list">',
  '        {items.map((it) => (',
  '          <li key={it.product_id}>',
  '            <span>{it.product.name}</span>',
  '            <div className="qty">',
  '              <button type="button" onClick={() => onQty(it.product_id, it.quantity - 1)}>−</button>',
  '              <span>{it.quantity}</span>',
  '              <button type="button" onClick={() => onQty(it.product_id, it.quantity + 1)}>+</button>',
  '            </div>',
  '            <b>{money(it.product.price * it.quantity)}</b>',
  '          </li>',
  '        ))}',
  '      </ul>',
  '      {items.length > 0 && (',
  '        <p className="total"><b>Итого: {money(subtotal)}</b></p>',
  '      )}',
  '    </div>',
  '  );',
  '}',
].join('\n');

const COMPONENT_CHECKOUT = [
  "import { useState } from 'react';",
  "import { createStoreOrder } from '../lib/kartaApi.js';",
  '',
  'const PHONE_RE = /^\\+?[0-9() -]{7,20}$/;',
  '',
  'export default function Checkout({ items, settings, onDone }) {',
  '  const [name, setName] = useState("");',
  '  const [phone, setPhone] = useState("");',
  '  const [address, setAddress] = useState("");',
  '  const [pickup, setPickup] = useState(false);',
  '  const [payment, setPayment] = useState("cash");',
  '  const [busy, setBusy] = useState(false);',
  '  const [message, setMessage] = useState(null);',
  '',
  '  const providers = settings.payment?.providers || ["cash"];',
  '  const canSubmit = items.length > 0 && name.trim() && PHONE_RE.test(phone)',
  '    && (pickup || address.trim()) && !busy;',
  '',
  '  async function submit(e) {',
  '    e.preventDefault();',
  '    if (!canSubmit) return;',
  '    setBusy(true);',
  '    setMessage(null);',
  '    try {',
  '      const result = await createStoreOrder({',
  '        items: items.map((it) => ({ product_id: it.product_id, quantity: it.quantity })),',
  '        customer: { name: name.trim(), phone: phone.trim() },',
  '        delivery: { type: pickup ? "pickup" : "delivery", address: pickup ? "" : address.trim() },',
  '        paymentMethod: payment,',
  '      });',
  '      setMessage({ ok: true, text: `Заказ №${String(result.order_id).slice(0, 8)} принят. Сумма: ${result.total} TJS` });',
  '      onDone();',
  '    } catch (err) {',
  '      setMessage({ ok: false, text: err.message });',
  '    } finally {',
  '      setBusy(false);',
  '    }',
  '  }',
  '',
  '  if (items.length === 0) return null;',
  '',
  '  return (',
  '    <form className="checkout" onSubmit={submit}>',
  '      <h2>Оформление заказа</h2>',
  '      <input value={name} onChange={(e) => setName(e.target.value)} placeholder="Имя" required />',
  '      <input value={phone} onChange={(e) => setPhone(e.target.value)} placeholder="+992 …" required />',
  '      <label className="row">',
  '        <input type="checkbox" checked={pickup} onChange={(e) => setPickup(e.target.checked)} />',
  '        Самовывоз',
  '      </label>',
  '      {!pickup && (',
  '        <input value={address} onChange={(e) => setAddress(e.target.value)} placeholder="Адрес доставки" required />',
  '      )}',
  '      <label>',
  '        Способ оплаты:',
  '        <select value={payment} onChange={(e) => setPayment(e.target.value)}>',
  '          {providers.includes("cash") && <option value="cash">Наличными</option>}',
  '          {providers.includes("card") && <option value="card">Картой при получении</option>}',
  '        </select>',
  '      </label>',
  '      <button className="btn" type="submit" disabled={!canSubmit}>',
  '        {busy ? "Отправка…" : "Заказать"}',
  '      </button>',
  '      {message && (',
  '        <p className={message.ok ? "ok" : "error"}>{message.text}</p>',
  '      )}',
  '    </form>',
  '  );',
  '}',
].join('\n');

const COMPONENT_DELIVERY = [
  'export default function Delivery({ settings, subtotal }) {',
  '  const d = settings.delivery || {};',
  '  if (d.enabled === false) return null;',
  '  const freeFrom = Number(d.free_from);',
  '  const free = Number.isFinite(freeFrom) && freeFrom > 0 && subtotal >= freeFrom;',
  '  const price = d.mode === "free" || free ? 0 : Number(d.price) || 0;',
  '  return (',
  '    <section className="info">',
  '      <h2>Доставка</h2>',
  '      <ul>',
  '        <li>Радиус: {Number(d.radius_km) || 10} км</li>',
  '        <li>{price > 0 ? `Стоимость: ${price} TJS` : "Бесплатно"}</li>',
  '        {Number(d.min_order) > 0 && <li>Минимальный заказ: {Number(d.min_order)} TJS</li>}',
  '        {Number.isFinite(freeFrom) && freeFrom > 0 && (',
  '          <li>Бесплатная доставка от {freeFrom} TJS</li>',
  '        )}',
  '      </ul>',
  '    </section>',
  '  );',
  '}',
].join('\n');

const COMPONENT_PAYMENT = [
  'const LABELS = {',
  '  cash: "Наличными при получении",',
  '  card: "Картой при получении",',
  '  alif: "Alif Pay",',
  '  eskhata: "Эсхата Pay",',
  '  dushanbe_city: "Dushanbe City",',
  '};',
  '',
  'export default function Payment({ settings }) {',
  '  const p = settings.payment || {};',
  '  const providers = p.providers || [];',
  '  if (providers.length === 0) return null;',
  '  return (',
  '    <section className="info">',
  '      <h2>Оплата</h2>',
  '      <ul>{providers.map((id) => <li key={id}>{LABELS[id] || id}</li>)}</ul>',
  '    </section>',
  '  );',
  '}',
].join('\n');

const COMPONENT_FOOTER = [
  'export default function Footer({ store }) {',
  '  const origin = (import.meta.env.VITE_KARTA_API_URL || "").replace(/\\/$/, "");',
  '  return (',
  '    <footer className="footer">',
  '      <p>{store.name}{store.address ? ` · ${store.address}` : ""}</p>',
  '      {store.phone && <p><a href={`tel:${store.phone}`}>{store.phone}</a></p>}',
  '      {origin && <p><a href={origin} target="_blank" rel="noreferrer">Сделано в Karta-AD</a></p>}',
  '    </footer>',
  '  );',
  '}',
].join('\n');

const STYLES_CSS = [
  ':root {',
  '  --bg: #0b1020;',
  '  --card: #141b33;',
  '  --fg: #eef2ff;',
  '  --muted: #9aa4c7;',
  '  --accent: #7c3aed;',
  '  --radius: 14px;',
  '}',
  '* { box-sizing: border-box; }',
  'body {',
  '  margin: 0;',
  "  font-family: Inter, system-ui, -apple-system, 'Segoe UI', sans-serif;",
  '  background: var(--bg);',
  '  color: var(--fg);',
  '}',
  '.header {',
  '  position: sticky; top: 0; z-index: 5;',
  '  display: flex; align-items: center; justify-content: space-between;',
  '  padding: 14px 20px;',
  '  background: rgba(11, 16, 32, 0.9);',
  '  backdrop-filter: blur(8px);',
  '  border-bottom: 1px solid #1f2947;',
  '}',
  '.logo { font-weight: 800; }',
  '.page { max-width: 1080px; margin: 0 auto; padding: 24px 20px 64px; }',
  '.hero { padding: 48px 0 24px; }',
  '.hero h1 { font-size: clamp(28px, 5vw, 44px); margin: 0 0 12px; }',
  '.muted { color: var(--muted); }',
  '.btn {',
  '  display: inline-block; border: 0; cursor: pointer;',
  '  background: var(--accent); color: #fff;',
  '  padding: 10px 18px; border-radius: var(--radius);',
  '  font-weight: 700; text-decoration: none;',
  '}',
  '.btn:disabled { opacity: 0.5; cursor: default; }',
  '.btn.ghost { background: transparent; border: 1px solid #2b3560; color: var(--fg); }',
  '.grid { display: grid; gap: 16px; grid-template-columns: repeat(auto-fill, minmax(220px, 1fr)); }',
  '.card { background: var(--card); border-radius: var(--radius); padding: 16px; display: grid; gap: 8px; }',
  '.card img { width: 100%; height: 140px; object-fit: cover; border-radius: 8px; }',
  '.qty { display: inline-flex; align-items: center; gap: 10px; }',
  '.qty button { width: 30px; height: 30px; border-radius: 8px; border: 1px solid #2b3560; background: transparent; color: var(--fg); cursor: pointer; }',
  '.info { background: var(--card); border-radius: var(--radius); padding: 18px; margin-top: 24px; }',
  '.overlay { position: fixed; inset: 0; background: rgba(0,0,0,0.55); display: flex; justify-content: flex-end; }',
  '.sheet {',
  '  width: min(440px, 100%); height: 100%; overflow-y: auto;',
  '  background: var(--bg); padding: 18px; display: grid; gap: 16px; align-content: start;',
  '}',
  '.cart-head { display: flex; justify-content: space-between; align-items: center; }',
  '.cart-list { list-style: none; margin: 0; padding: 0; display: grid; gap: 10px; }',
  '.cart-list li { display: flex; align-items: center; gap: 10px; justify-content: space-between; }',
  '.checkout { display: grid; gap: 10px; }',
  '.checkout input, .checkout select {',
  '  padding: 10px 12px; border-radius: 8px;',
  '  border: 1px solid #2b3560; background: var(--card); color: var(--fg);',
  '}',
  '.row { display: flex; gap: 8px; align-items: center; }',
  '.ok { color: #34d399; }',
  '.error { color: #f87171; }',
  '.footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #1f2947; color: var(--muted); font-size: 14px; }',
  '.footer a { color: var(--muted); }',
].join('\n');

/** Все известные маски секретов — не должны попасть ни в один файл. */
export const SECRET_PATTERNS = [
  /SERVICE_ROLE/i,
  /PAYMENT_SECRET/i,
  /OPENROUTER/i,
  /sk-or-/,
  /sb_secret_/,
  /sbp_[a-z0-9]/i,
];

/** Найти файлы с секретами: [{path, pattern}] — пусто = чисто. */
export function findSecrets(files) {
  const hits = [];
  for (const [path, content] of Object.entries(files || {})) {
    if (typeof content !== 'string') continue;
    for (const re of SECRET_PATTERNS) {
      if (re.test(content)) hits.push({ path, pattern: String(re) });
    }
  }
  return hits;
}
