import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// Cache map tiles (Karta-AD: CARTO, Google, OSM-fallback, self-hosted /tiles/)
registerRoute(
  ({ url }) =>
    url.origin.includes('tile.openstreetmap.org') ||
    url.origin.includes('basemaps.cartocdn.com') ||
    url.origin.includes('mt0.google.com') ||
    url.pathname.includes('/tiles/'),
  new CacheFirst({
    cacheName: 'map-tiles',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 500,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Cache critical route data from API
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/routes') || url.pathname.startsWith('/api/stops'),
  new StaleWhileRevalidate({
    cacheName: 'route-data',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 24 * 60 * 60, // 1 day
      }),
    ],
  })
);
